export default {
  baseUrl: prod ? 'https://bog-npp.now.sh' : 'http://localhost:3000',
  dbUrl: 'mongodb://localhost:27017',
  dbName: 'Items',
//   apis: {
//     getItems: '/api/getItems',
//     addItem: '/api/addItem',
//     deleteItem: '/api/deleteItem',
//     getItem: '/api/getItem',
//     updateItemState: '/api/updateItemState',
//     updateItemDecision: '/api/updateItemDecision',
//     updateItemMeeting: '/api/updateItemMeeting',
//     getAvailabilities: '/api/getAvailabilities',
//     addAvailability: '/api/addAvailability',
//     deleteAvailability: '/api/deleteAvailability',
//     getAvailability: '/api/getAvailability',
//     updateAvailability: '/api/updateAvailability',
//     login: '/api/login',
//     signUp: '/api/signUp',
//     verifyToken: '/api/verifyToken',
//   },
//   pages: {
//     Item: '/',
//     login: '/login',
//     register: '/register',
//     submitted: '/submitted',
//     admin: '/admin',
//     availability: '/availability',
//   },
};